### ISSUE TITLE
Commit after all messages got processed

### ISSUE THREAD

**Issue by roymiloh** [nodefluent/kafka-connect#12]
Hi,

I'm having a small question - I'm trying to understand how batching works here. Does it mean that the fetch will (potentially) retrieve multiple messages only? what about committing them all together (so we can have at-least-once policy)? is it something that existing?

For instance - [here](https://github.com/nodefluent/kafka-connect/blob/master/lib/sink/SinkConfig.js#L227), it looks like that only one offset will be committed at a time. And if we take a look at the [gcloud pubsub sink impl](https://github.com/nodefluent/gcloud-pubsub-kafka-connect/blob/619a21503875ae13fae232a8dbf40f42dfd88296/lib/sink/PubSubSinkTask.js#L110) it seems like all messages are stored in memory and getting processed only when `buffer > batchSize`, so if the server is down for some reason, all messages will be gone because their offset already committed (so no at-least-once policy here).

Also, does [`config.batch`](https://github.com/nodefluent/kafka-connect/commit/c97fc1e56a08df55752513f633377430db1c9ba1) only have guarantee on minimum bytes or something like that?

Thanks!

**Comment by krystianity** [comment]
If the native consumer is used (depends on the config that is passed to the clients and if node-rdkafka is installed successfully) batches will be pulled into memory, but should only be committed once all messages have been processed successfully (depending on retry strategy). 

Which means that even if the consumer dies with a batch in memory, it should consume the same messages after a restart from kafka, so at-least-once should be guaranteed. But of course this also depends on the connector implementation.

Sorry for the late reply.
