### ISSUE TITLE
You have to install node-rdkafka to use NProducer

### ISSUE THREAD

**Issue by zeeshanalisyed** [nodefluent/kafka-connect#51]
Test is failing because node-rdkafka is not the part of dependencies in package.json file

![node-rdkakfa-missing](https://user-images.githubusercontent.com/8758274/90367451-f0923600-e079-11ea-9086-9e7f2fa1cbd3.png)
now After installing node-rdkakfa
![node-rdkafka-added](https://user-images.githubusercontent.com/8758274/90367782-3a7b1c00-e07a-11ea-948c-2db749581b32.png)

Now My Question is Why this wasn't added into package.json dependencies because this way developer have to install node-rdkafka again and again where ever he/she wants to use this package

**Comment by rob3000** [comment]
Hi @zeeshanalisyed , 

The reason `node-rdkafka` isn't bundled with kafka-connect is thats its an optional dependency see: https://github.com/nodefluent/kafka-connect#a-note-on-native-mode
